/*
 * Title
 * Title
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.coursesdemo.api;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;

public class Student   {

    private String name = null;


    private Integer age = null;


    private Boolean member = null;


    private List<String> languages = null;

    public Student name(String name) {
        this.name = name;
        return this;
    }

    /**
     * name of the student
     * @return name
     **/
    @JsonProperty("name")
    @Schema(description = "name of the student")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Student age(Integer age) {
        this.age = age;
        return this;
    }

    /**
     * age of the student
     * @return age
     **/
    @JsonProperty("age")
    @Schema(description = "age of the student")
    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public Student member(Boolean member) {
        this.member = member;
        return this;
    }

    /**
     * has the student taken membership
     * @return member
     **/
    @JsonProperty("member")
    @Schema(description = "has the student taken membership")
    public Boolean isMember() {
        return member;
    }

    public void setMember(Boolean member) {
        this.member = member;
    }

    public Student languages(List<String> languages) {
        this.languages = languages;
        return this;
    }

    public Student addLanguagesItem(String languagesItem) {
        if (this.languages == null) {
            this.languages = new ArrayList<String>();
        }
        this.languages.add(languagesItem);
        return this;
    }

    /**
     * array of languages
     * @return languages
     **/
    @JsonProperty("languages")
    @Schema(description = "array of languages")
    public List<String> getLanguages() {
        return languages;
    }

    public void setLanguages(List<String> languages) {
        this.languages = languages;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Student student = (Student) o;
        return Objects.equals(this.name, student.name) &&
                Objects.equals(this.age, student.age) &&
                Objects.equals(this.member, student.member) &&
                Objects.equals(this.languages, student.languages);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, age, member, languages);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Student {\n");

        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    age: ").append(toIndentedString(age)).append("\n");
        sb.append("    member: ").append(toIndentedString(member)).append("\n");
        sb.append("    languages: ").append(toIndentedString(languages)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
